[toolchain]
channel = "1.93.0"
components = ["rustfmt", "clippy", "rust-src", "rust-analyzer", "llvm-tools-preview"]
targets = ["wasm32-unknown-unknown"]
# by 'make install-tools' for cargo-llvm-cov code coverage support
